CREATE DATABASE product_recommendation;

CREATE TABLE product_recommendation.data (
    `fecha_dato` VARCHAR(50) NULL COMMENT 'Data date',
    `ncodpers` INT NULL COMMENT 'Customer code',
    `ind_empleado` VARCHAR(50) NULL COMMENT 'Employee index',
    `pais_residencia` VARCHAR(50) NULL COMMENT 'Residence country',
    `sexo` VARCHAR(50) NULL COMMENT 'Gender',
    `age` VARCHAR(50) NULL COMMENT 'Age',
    `fecha_alta` VARCHAR(50) NULL COMMENT 'Registration date',
    `ind_nuevo` VARCHAR(50) NULL COMMENT 'New customer index',
    `antiguedad` VARCHAR(50) NULL COMMENT 'Seniority',
    `indrel` VARCHAR(50) NULL COMMENT 'Customer relation index',
    `ult_fec_cli_1t` VARCHAR(50) NULL COMMENT 'Last date as primary customer',
    `indrel_1mes` DOUBLE NULL COMMENT 'Customer relation index in the last month',
    `tiprel_1mes` VARCHAR(50) NULL COMMENT 'Customer relation type in the last month',
    `indresi` VARCHAR(50) NULL COMMENT 'Residence index',
    `indext` VARCHAR(50) NULL COMMENT 'Foreigner index',
    `conyuemp` VARCHAR(50) NULL COMMENT 'Spouse employed index',
    `canal_entrada` VARCHAR(50) NULL COMMENT 'Entry channel',
    `indfall` VARCHAR(50) NULL COMMENT 'Deceased index',
    `tipodom` VARCHAR(50) NULL COMMENT 'Home type',
    `cod_prov` VARCHAR(50) NULL COMMENT 'Province code',
    `nomprov` VARCHAR(50) NULL COMMENT 'Province name',
    `ind_actividad_cliente` VARCHAR(50) NULL COMMENT 'Customer activity index',
    `renta` DOUBLE NULL COMMENT 'Income',
    `segmento` VARCHAR(50) NULL COMMENT 'Segment',
    `ind_ahor_fin_ult1` INT NULL COMMENT 'Savings account',
    `ind_aval_fin_ult1` INT NULL COMMENT 'Guarantee',
    `ind_cco_fin_ult1` INT NULL COMMENT 'Current account',
    `ind_cder_fin_ult1` INT NULL COMMENT 'Derivatives account',
    `ind_cno_fin_ult1` INT NULL COMMENT 'Payroll account',
    `ind_ctju_fin_ult1` INT NULL COMMENT 'Junior account',
    `ind_ctma_fin_ult1` INT NULL COMMENT 'More particular account',
    `ind_ctop_fin_ult1` INT NULL COMMENT 'Particular account',
    `ind_ctpp_fin_ult1` INT NULL COMMENT 'Prime account',
    `ind_deco_fin_ult1` INT NULL COMMENT 'Short-term deposits',
    `ind_deme_fin_ult1` INT NULL COMMENT 'Medium-term deposits',
    `ind_dela_fin_ult1` INT NULL COMMENT 'Long-term deposits',
    `ind_ecue_fin_ult1` INT NULL COMMENT 'E-account',
    `ind_fond_fin_ult1` INT NULL COMMENT 'Funds',
    `ind_hip_fin_ult1` INT NULL COMMENT 'Mortgage',
    `ind_plan_fin_ult1` INT NULL COMMENT 'Pensions',
    `ind_pres_fin_ult1` INT NULL COMMENT 'Loans',
    `ind_reca_fin_ult1` INT NULL COMMENT 'Taxes',
    `ind_tjcr_fin_ult1` INT NULL COMMENT 'Credit Card',
    `ind_valo_fin_ult1` INT NULL COMMENT 'Securities',
    `ind_viv_fin_ult1` INT NULL COMMENT 'Home Account',
    `ind_nomina_ult1` VARCHAR(50) NULL COMMENT 'Payroll',
    `ind_nom_pens_ult1` VARCHAR(50) NULL COMMENT 'Pensions2',
    `ind_recibo_ult1` INT NULL COMMENT 'Direct Debit'
)
ENGINE = OLAP
DUPLICATE KEY(`fecha_dato`, `ncodpers`)  -- Added DUPLICATE KEY
DISTRIBUTED BY HASH(`fecha_dato`, `ncodpers`) BUCKETS 20
;
